### ISSUE TITLE
parallel doesnt work on custom functions

### ISSUE THREAD

**Issue by brunocarlin** [earowang/hts#44]
forecast.gts(
    htseg1, h = 10, method = "comb", algorithms = "lu",weights = "mint",
  FUN = function(x) snaive(x), parallel = T,num.cores = 2
)

**Comment by yasineahmed** [comment]
any updates on this? 
trying to use BaggedETS

**Comment by yasineahmed** [comment]
From what I understand to get a function to work in parallel have to clusterexport() the function to globalEnv. Correct me if I am wrong.

Thank you.

**Comment by yasineahmed** [comment]
work around solution would be to add needed libraries using clusterEvalQ
