### ISSUE TITLE
Interop with tidyverts

### ISSUE THREAD

**Issue by Hong-Revo** [earowang/hts#49]
Hi,

This is some great work here. I noticed though, that it's still based on the forecast framework. Are there any plans to port it to tidyverts or make a replacement? Or has this been done already?

**Comment by robjhyndman** [comment]
See the `reconcile` function in the `fable` package.

**Comment by Hong-Revo** [comment]
@robjhyndman There's no `fable::reconcile`, did you mean `fabletools::reconcile`? I don't see how it's relevant here.

**Comment by robjhyndman** [comment]
Yes. It provides the same facilities as the hts package. See https://github.com/rstudio-conf-2020/time-series-forecasting/raw/master/materials/10-reconciliation.pdf for some examples

**Comment by Hong-Revo** [comment]
Thanks. I'm getting the feeling the documentation is a work in progress....

**Comment by robjhyndman** [comment]
Yes. The best source right now is probably otexts.com/fpp3, but that does not yet include reconciliation.

**Comment by mitchelloharawild** [comment]
@earowang 
Consider retiring this package and text to the README (similar to [robjhyndman/forecast](https://github.com/robjhyndman/forecast/)) pointing people to the reconciliation functionality in fabletools?
