### ISSUE TITLE
hts cannot create a hierarchical time series for a single observation

### ISSUE THREAD

**Issue by mahdiabolghasemi** [earowang/hts#57]
It seems that hts cannot create a hierarchical time series if we have only one observation in the series. 
It returns: Error in if (nbts <= 1L) { : argument is of length zero

library(hts)

nodes <- list(2, c(3, 2))
abc <- ts(5 + matrix(sort(rnorm(500)), ncol = 5, nrow = 100))
y <- hts(abc[1,], nodes)

**Comment by earowang** [comment]
You need to subset with `drop = FALSE` to retain the `ts` object, otherwise `abc[1, ]` is a numeric vector, not an `mts`.

``` r
library(hts)
#> Loading required package: forecast
#> Registered S3 method overwritten by 'quantmod':
#>   method            from
#>   as.zoo.data.frame zoo

nodes <- list(2, c(3, 2))
abc <- ts(5 + matrix(sort(rnorm(500)), ncol = 5, nrow = 100))
hts(abc[1, , drop = FALSE], nodes)
#> Since argument characters are not specified, the default labelling system is used.
#> Hierarchical Time Series 
#> 3 Levels 
#> Number of nodes at each level: 1 2 5 
#> Total number of series: 8 
#> Number of observations per series: 1 
#> Top level series: 
#> Time Series:
#> Start = 1 
#> End = 1 
#> Frequency = 1 
#> [1] 22.10018
```

<sup>Created on 2020-08-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
